export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_OK = 'ADD_PRODUCT_OK';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_OK = 'GET_PRODUCTS_OK';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const GET_PRODUCT_TO_DELETE  = 'GET_PRODUCT_TO_DELETE';
export const GET_PRODUCT_TO_DELETE_OK  = 'GET_PRODUCT_TO_DELETE_OK';
export const GET_PRODUCT_TO_DELETE_ERROR  = 'GET_PRODUCT_TO_DELETE_ERROR';

export const GET_PRODUCT_TO_MODIFY  = 'GET_PRODUCT_TO_MODIFY';
export const GET_PRODUCT_TO_MODIFY_START = 'GET_PRODUCT_TO_MODIFY_START';
export const GET_PRODUCT_TO_MODIFY_OK  = 'GET_PRODUCT_TO_MODIFY_OK';
export const GET_PRODUCT_TO_MODIFY_ERROR  = 'GET_PRODUCT_TO_MODIFY_ERROR';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';
